name: 'order'
description: 'Prints Hello, World!'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: "Print Hello World"
      run: echo "Hello, World!"
      shell: bash